travis:
  secure:
    BINSTAR_TOKEN: njjqNE3fgIgAa0e4Oe+0DoO4w2ET5ZpvjHXfXv6YwoLX33MnSfMmtKP9I4JtixKkZxBt9qG2cSTEIhdSWWo5bOHSruXinlNYfI0tzCrXQeNoveONkmi53KkCPgXxI4vqgOG4wv33PApgrlEgOi4vIW/xAa+0NwpLN7qPnrGiAJKqsGZLF1x4rTZ0Yr9K7VjNxMfZpATZXyoVZ9Ah3EXYneV1XULPsQAcrdDk+1mprgtndyaQ1mbVaQ+tJvqnHwGQvLT9S+fb6PWZKJBSKHUHQJr9XolpIjeR2Z/FYfLnyFE5cIHQki3IfgHcoOgILTHI0z4I0EJyOlkrVYb9+RRvaIVZ4lX8e83958EbTqb0kRZfZw3KrOoQFoR5atrolHghe9Fw5uDxryjPJhaXnVYXUeE+mBzYVKmUcDz3+mhNJiZOX68+TqnBX+49hqsfHB4FOBQL7YqEUYXeSu2iNOquhFVAyLNwZtOGaRR/k2KtmKYmW6QNPluLzB8hMTK2R5p95+79Gkp50MjdxG8k9C53+3gjFX1mld8/WQdeTohWlY0cPUL8dnYWDzqHSP72pDUvps4gPfAey+k4D9QACyHCCA+VtWHHKFgncVWqr0xvwUwuJV+oD+wLkMoEQz1Eu0EQyUQLczuupNXeI4FlF6sqXP1FfABfxaCKz+nFBNfV8sQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
